### ISSUE TITLE
Support for Wine and AppImages.

### ISSUE THREAD

**Issue by Abhinav1217** [BenJetson/gnome-dash-fix#2]
First of all Thanks a lot.  This saves me a lot of time. I had to manually create folders in gnome-software and assign apps in it. This was the first time I felt that gnome-softwares is a bad piece of software. And I had freshly installed fedora few days ago.

Another thanks because it supports chrome-apps.  That was the one thing I could never get to go into the folder. Confusingly I had unsuccessfully used the same commands for chrome app which is in your script and is now working.

Now for issues.   Only thing left unsorted are `wine apps` and apps I have installed using `.AppImage` packaging. 

Here is a screenshot.
![screenshot from 2017-04-28 10-45-17](https://cloud.githubusercontent.com/assets/740584/25515100/b730ffb4-2bd1-11e7-8fba-a4c5ed9f9210.png)
![screenshot from 2017-04-28 10-46-00](https://cloud.githubusercontent.com/assets/740584/25515109/cb1efba2-2bd1-11e7-834b-f1b29916b713.png)

I mark this as issue because softwares `"Balsamiq" installed via wine` and `"Freeter", "Sqltron", "Gravit" installed via .AppImage` were previously located to a custom folder named "Development Tools" I created via gnome-softwares.  Now as you can see above, They are outside of any folder and my custom folder is no were to be seen.

**Comment by BenJetson** [comment]
Hey! Just a while ago, I uploaded a new script that allows for further customization of categories. Since use of WINE is so common, I went ahead and added it to both the old script and new script as a default.

If you use the new script, it will overwrite the old configuration for you automatically (unfortunately along with user-created categories).

I have never personally dealt with AppImages, but from what I understand they behave like traditional apps and should be categorized like traditional apps (ex. an AppImage of GIMP should still be in Graphics).

Maybe the developer didn't specify categories in their `.desktop` file? Could you post a `.desktop` file for one of the apps you're having trouble with? You can usually find system-wide launcher files at `/usr/share/applications` and user-only launcher files at `~/.local/share/applications`. I just need the text from inside the file.

Let me know how it goes.

**Comment by Abhinav1217** [comment]
By default, appimage create `.desktop` file only for the current user. You were right, Type of all the AppImage packaging is `Application`. It is up to the packager to write a proper attributes in .desktop file so I guess there is not much we can do without manually editing.

Here is cat of .desktop some of the appimage file and some of the wine file.

```
[Abhinav@fedora-25 applications] $ pwd
/home/Abhinav/.local/share/applications
[Abhinav@fedora-25 applications] $ cat appimagekit-cerebro.desktop 
[Desktop Entry]
Name=Cerebro
Comment=Extendable electron-based open-source Spolight and Alfred analogue
Exec="/home/Abhinav/Downloads/cerebro-0.2.7-x86_64.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-cerebro
X-AppImage-Version=0.2.7
X-AppImage-BuildId=fac4a520-00c8-11a7-39cd-4be056a685f5
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_sw49RF/AppRun
TryExec=/home/Abhinav/Downloads/cerebro-0.2.7-x86_64.AppImage
[Abhinav@fedora-25 applications] $ cat appimagekit-gravit-designer.desktop 
[Desktop Entry]
Name=Gravit Designer
Comment=Gravit Designer is a full featured free vector design app right at your fingertip.
Exec="/home/Abhinav/Desktop/GravitDesigner.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-gravit-designer
X-AppImage-Version=3.0.4.1633
X-AppImage-BuildId=2c8b3160-2058-11a7-0be1-2de0762a3fe8
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_LiIZMl/AppRun
TryExec=/home/Abhinav/Desktop/GravitDesigner.AppImage
[Abhinav@fedora-25 applications] $ cat wine/Programs/Balsamiq\ Mockups\ 3.desktop 
[Desktop Entry]
Name=Balsamiq Mockups 3
Exec=env WINEPREFIX="/home/Abhinav/.wine" /usr/bin/wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/Abhinav/.wine/dosdevices/c:/users/Abhinav/Start\\ Menu/Programs/Balsamiq\\ Mockups\\ 3.lnk
Type=Application
StartupNotify=true
Icon=8BE2_Balsamiq Mockups 3.0
[Abhinav@fedora-25 applications] $
```

Maybe they can be sorted by filtering `WINEPREFIX` for wine apps and `appimagekit-` for AppImage stuffs.

**Comment by Abhinav1217** [comment]
I just used your new interactive python script.  And also the older shell script.   Wine Apps are still not into the folders. Python script did create an empty AppImage folder.

You should add shebang `#!/usr/bin/python3`  in your python script so that it can be run directly by `./interactive.py`

**Comment by BenJetson** [comment]
Odd. The Wine apps on my system appear in the folder like they should:
![image](https://cloud.githubusercontent.com/assets/10427974/25556291/f60f6b66-2cc7-11e7-990f-35f1c7a138fc.png)

Post an uncategorized Wine `.desktop` file on your system that causes the issue and I'll try to figure it out.
On my system, all of the Wine applications have one of these two lines in their `.desktop` entry:
![image](https://cloud.githubusercontent.com/assets/10427974/25556337/83156e48-2cc8-11e7-8689-d9d01b6ae689.png) ![image](https://cloud.githubusercontent.com/assets/10427974/25556330/70022d5a-2cc8-11e7-8cc7-c5904a0208da.png)

As for the AppImages, the problem is the developer's negligence to specify the categories as I'd suspected. To fix this, you can either manually add them to the correct folder via GNOME Software, or add the line `Categories=<CATEGORY>;` to the `.desktop` file. For info about which categories are added by default, see the [Default Folders wiki entry](https://github.com/BenJetson/gnome-dash-fix/wiki/Default-Folders).

Also, thanks for the tip about adding the shebang. I'd completely forgotten to do that. :smiley:

**Comment by Abhinav1217** [comment]
Here is the cat for `wine file` which is installed as default when installing wine.
```
[Abhinav@fedora-25 ~] $ cat /usr/share/applications/wine-winefile.desktop
[Desktop Entry]
Name=Wine File
Comment=Wine File Browser
Name[ar]=مدير ملفات واين
Comment[ar]=إدارة الملفات بطريقة واين
Exec=winefile
Icon=winefile
Terminal=false
Type=Application
Categories=X-Wine;
X-Desktop-File-Install-Version=0.23
```
Thing is that they were inside folder before I used your script. That was why I logged this issue.
All wine Items were inside a folder named `wine items` except for balsamiq, because its .desktop file did not contain `Catgories` section. But once I added that line, it was sorted into the `wine items` folder

Here is the content of Balsamiq.desktop
```
[Abhinav@fedora-25 ~] $ cat "/home/Abhinav/.local/share/applications/wine/Programs/Balsamiq Mockups 3.desktop"
[Desktop Entry]
Name=Balsamiq Mockups 3
Exec=env WINEPREFIX="/home/Abhinav/.wine" /usr/bin/wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/Abhinav/.wine/dosdevices/c:/users/Abhinav/Start\\ Menu/Programs/Balsamiq\\ Mockups\\ 3.lnk
Type=Application
Categories=X-Wine;Wine;Development"
StartupNotify=true
Icon=8BE2_Balsamiq Mockups 3.0

```
Some other info about my system which might help you. 
```
[Abhinav@fedora-25 ~] $ uname -a
Linux fedora-25 4.10.12-200.fc25.x86_64 #1 SMP Sat Apr 22 03:03:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[Abhinav@fedora-25 ~] $ gnome-shell --version
GNOME Shell 3.22.3
[Abhinav@fedora-25 ~] $ wine --version
wine-2.6 (Staging)
```

**Comment by BenJetson** [comment]
Aha! That explains the problem the problem. :smiley: 

I've added the `X-Wine` category to the Wine folder on both the new script (e302cdb71410c193c4ade40e8e20529e7e53106d) and old script (2614b13e2d4d70225d0dc3ae8be1cc307c02c362).

That should fix it. Run the script again and let me know how it goes.

**Comment by Abhinav1217** [comment]
Works great. Only icons remaining outside of folders are those who do not have `Categories` in their .desktop file.  I will someday find time to fix that.  Great work. Thanks.
The shell script is going to my Setup script. It is a script I created to run on a fresh install system and do my personalization.  Thanks,

**Comment by BenJetson** [comment]
Neat. Glad I could help. 😄
